version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      - VITE_API_BASE_URL=https://fiap-fsdt-techchallenge-ii-posts.onrender.com
    networks:
      - blog-network
    depends_on:
      - backend
    restart: unless-stopped

  # Serviço do backend (assumindo que existe)
  backend:
    # Esta configuração assumirá que o backend está em ../backend
    # Ajuste conforme necessário
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/blog-professores
    networks:
      - blog-network
    depends_on:
      - mongo
    restart: unless-stopped

  # Banco de dados MongoDB
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=blog-professores
    volumes:
      - mongo_data:/data/db
    networks:
      - blog-network
    restart: unless-stopped

volumes:
  mongo_data:

networks:
  blog-network:
    driver: bridge
