version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:3000
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    external: true
    name: blog-network
